export const activitiesArray = [
    {
      image: "/activities.svg",
      name: "The Museum of Modern Art",
      description: "Works from Van Gogh to Warhol & beyond plus a sculpture garden, 2 cafes & modern restaurant",
      rating: "4.5(436)",
      size: "1 hour",
      time: "10:30am",
      date: "Mar 19",
      included: "Admission to the Empire State Building",
      day: "1",
      price: "123,450.00",
    },
    {
      image: "/activities.svg",
      name: "The Museum of Modern Art",
      description: "Works from Van Gogh to Warhol & beyond plus a sculpture garden, 2 cafes & modern restaurant",
      rating: "4.5(436)",
      size: "1 hour",
      time: "10:30am",
      date: "Mar 19",
      included: "Admission to the Empire State Building",
      day: "1-(2)",
      price: "123,450.00",
    },
    {
      image: "/activities.svg",
      name: "The Museum of Modern Art",
      description: "Works from Van Gogh to Warhol & beyond plus a sculpture garden, 2 cafes & modern restaurant",
      rating: "4.5(436)",
      size: "1 hour",
      time: "10:30am",
      date: "Mar 19",
      included: "Admission to the Empire State Building",
      day: "2",
      price: "123,450.00",
    },
  ]